# Configurar secrets.toml para dlt
[sources.sql_database.credentials]
drivername = {env = "SOURCE__MYSQL__CREDENTIALS__DRIVERNAME" } # fill this in!
database = {env = "SOURCE__MYSQL__CREDENTIALS__DATABASE" } # fill this in!
password = {env = "SOURCE__MYSQL__CREDENTIALS__PASSWORD" } # fill this in!
username = {env = "SOURCE__MYSQL__CREDENTIALS__USERNAME" } # fill this in!
host = {env = "SOURCE__MYSQL__CREDENTIALS__HOST" } # fill this in!
port = {env = "SOURCE__MYSQL__CREDENTIALS__PORT" } # fill this in!

[destination.postgres.credentials]
database = {env = "DESTINATION__POSTGRES__CREDENTIALS__DATABASE" } # fill this in!
password = {env = "DESTINATION__POSTGRES__CREDENTIALS__PASSWORD" } # fill this in!
username = {env = "DESTINATION__POSTGRES__CREDENTIALS__USERNAME" } # fill this in!
host = {env = "DESTINATION__POSTGRES__CREDENTIALS__HOST" } # fill this in!
port = {env = "DESTINATION__POSTGRES__CREDENTIALS__PORT" }
connect_timeout = 15

